export const GET_ALL_PRODUCTS = 'PRODUCTS/GET_ALL_PRODUCTS';
export const GET_ALL_PRODUCTS_SUCCESS = 'PRODUCTS/GET_ALL_PRODUCTS_SUCCESS';
export const GET_ALL_PRODUCTS_FAILED = 'PRODUCTS/GET_ALL_PRODUCTS_FAILED';

export const GET_SINGLE_PRODUCT = 'PRODUCTS/GET_SINGLE_PRODUCT';
export const GET_SINGLE_PRODUCT_SUCCESS = 'PRODUCTS/GET_SINGLE_PRODUCT_SUCCESS';
export const GET_SINGLE_PRODUCT_FAILED = 'PRODUCTS/GET_SINGLE_PRODUCT_FAILED';
